//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Email { get; set; }
        public string ROL { get; set; }
        public string WACHTWOORD { get; set; }
        public string VOORNAAM { get; set; }
        public string INTITIALEN { get; set; }
        public string ACHTERNAAM { get; set; }
        public string WOONPLAATS { get; set; }
        public string STRAAT { get; set; }
        public string HUISNUMMER { get; set; }
        public string POSTCODE { get; set; }
        public string TELEFOONNUMMER { get; set; }
    
        public virtual Rol Rol1 { get; set; }
    }
}
