//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.QuizRondes = new HashSet<QuizRonde>();
            this.Teams = new HashSet<Team>();
        }
    
        public int EvenementID { get; set; }
        public int LocatieID { get; set; }
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email_Quizmaster { get; set; }
        [StringLength(100)]
        public string Evenement_Naam { get; set; }
        public System.DateTime Begintijd { get; set; }
        public System.DateTime Eindtijd { get; set; }
        [StringLength(50)]
        public string Evenement_Type { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Locatie Locatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizRonde> QuizRondes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
