//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.QuizRonde = new HashSet<QuizRonde>();
            this.Team = new HashSet<Team>();
        }
    
        public int EvenementID { get; set; }
        public int LocatieID { get; set; }
        public int AccountID { get; set; }
        public string Evenement_Naam { get; set; }
        public System.DateTime Begintijd { get; set; }
        public System.DateTime Eindtijd { get; set; }
        public string Evenement_Type { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Locatie Locatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizRonde> QuizRonde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team { get; set; }
    }
}
