//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.Rondes = new HashSet<Ronde>();
        }
    
        public int EvenementID { get; set; }
        public string Email { get; set; }
        public string Naam { get; set; }
        public string Plaatsnaam { get; set; }
        public string Locatie_Naam { get; set; }
        public System.DateTime BeginTijd { get; set; }
        public System.DateTime EindTijd { get; set; }
        public string Evenement_Type { get; set; }
    
        public virtual Locatie Locatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ronde> Rondes { get; set; }
    }
}
