//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeerkeuzeAntwoord
    {
        public string MeerkeuzeAntwoord1 { get; set; }
        public int VraagID { get; set; }
        public bool isJuist { get; set; }
    
        public virtual Vraag Vraag { get; set; }
    }
}
