//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizVraag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizVraag()
        {
            this.MeerkeuzeAntwoords = new HashSet<MeerkeuzeAntwoord>();
            this.TeamAntwoords = new HashSet<TeamAntwoord>();
            this.VraagInQuizs = new HashSet<VraagInQuiz>();
        }
    
        public int QuizVraagID { get; set; }
        public string Thema_Naam { get; set; }
        public string Vraag { get; set; }
        public string Vraagtype { get; set; }
        public string Open_Vraag_Antwoord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeerkeuzeAntwoord> MeerkeuzeAntwoords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamAntwoord> TeamAntwoords { get; set; }
        public virtual Thema Thema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VraagInQuiz> VraagInQuizs { get; set; }
    }
}
