//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QuizVraag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizVraag()
        {
            this.MeerkeuzeAntwoord = new HashSet<MeerkeuzeAntwoord>();
            this.TeamAntwoord = new HashSet<TeamAntwoord>();
            this.VraagInQuiz = new HashSet<VraagInQuiz>();
        }
    
        public int QuizVraagID { get; set; }
        public int ThemaID { get; set; }
        [StringLength(200)]
        public string Vraag { get; set; }
        public string Vraagtype { get; set; }
        [StringLength(100)]
        public string Open_Vraag_Antwoord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeerkeuzeAntwoord> MeerkeuzeAntwoord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamAntwoord> TeamAntwoord { get; set; }
        public virtual Thema Thema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VraagInQuiz> VraagInQuiz { get; set; }
    }
}
