//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stem
    {
        public string EMAIL { get; set; }
        public int EVENTID { get; set; }
        public string ARTIEST { get; set; }
        public string TITEL { get; set; }
    }
}
