//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.TeamAntwoords = new HashSet<TeamAntwoord>();
        }
    
        public int TeamID { get; set; }
        public int EvenementID { get; set; }
        public string Teamnaam { get; set; }
        public string Email_Teamleider { get; set; }
        public int Puntentotaal { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Evenement Evenement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamAntwoord> TeamAntwoords { get; set; }
    }
}
