//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamAntwoord
    {
        public int TeamAntwoordID { get; set; }
        public int TeamID { get; set; }
        public int QuizVraagID { get; set; }
        public string Gegeven_Antwoord { get; set; }
    
        public virtual QuizVraag QuizVraag { get; set; }
        public virtual Team Team { get; set; }
    }
}
