//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vraag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vraag()
        {
            this.MeerkeuzeAntwoord = new HashSet<MeerkeuzeAntwoord>();
            this.Ronde = new HashSet<Ronde>();
        }
    
        public int VraagID { get; set; }
        public string ThemaNaam { get; set; }
        public string Vraag1 { get; set; }
        public string Vraagtype { get; set; }
        public string AntwoordOpenVraag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeerkeuzeAntwoord> MeerkeuzeAntwoord { get; set; }
        public virtual Thema Thema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ronde> Ronde { get; set; }
    }
}
